language: php

sudo: required

dist: trusty

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

env:
  - V8VER=5.2

matrix:
  include:
    - php: "5.3"
      dist: precise

before_install:
  - php tests/travis.php before_install

install:
  - php tests/travis.php install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - php tests/travis.php after_script

after_success:
  - php tests/travis.php after_success

addons:
  code_climate:
    repo_token: 96050f995dc526f7ece7effce0b7c5a213d08b891e6ba8c086dad0864b76488c
