language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - apt-get install libv8-dev libv8-dbg g++ cpp
  - travis_retry php tests/installV8js.php
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 96050f995dc526f7ece7effce0b7c5a213d08b891e6ba8c086dad0864b76488c
